"use client";
import { useMemo, useState } from "react";

const DECK = [
 "Breakfast for dinner","A window seat","Fresh flowers","A long nap","Dancing in the kitchen","A surprise day off","Homemade cookies","A beach sunset","Winning an argument","A perfectly ripe mango","A road trip","A cozy blanket","Karaoke night","A handwritten note","The first sip of coffee","A clean house","Getting dressed up","A funny family story","A quiet morning","A spontaneous plan","A great bargain","Staying up too late","A home-cooked meal","A mystery novel","A warm rainstorm","Board game night","A new restaurant","An old photograph","No alarm tomorrow","A thoughtful gift","Being right","A long phone call","Freshly washed sheets","A movie marathon","A beautiful garden","A big family dinner","Trying something new","A second helping","A scenic train ride","A silly inside joke","A perfect playlist","Finishing a puzzle","An unexpected compliment","A lazy Sunday","A fancy dessert","A museum afternoon","A good hair day","A heartfelt hug",
 "Retiring somewhere warm","Building a dream home","Starting a family business","Learning a new language","Taking a family world tour","Creating a new holiday tradition","Living abroad for a year","Finally doing the biggest bucket-list dream","Hosting every future family gathering","Having a five-year plan that actually works",
 "Someone chewing too loudly","A text left on read for three days","The person who is always late","A thermostat battle","An empty container put back in the fridge","A wet towel left on the bed","A movie spoiler without warning","Clutter on every flat surface","An enthusiastic backseat driver","Being interrupted mid-story",
 "Coffee as a first date","Dinner as a first date","An adventurous surprise date","A perfectly planned date night","A completely spontaneous date","Public displays of affection","Making a shared romantic playlist","Wearing matching outfits","Leaving little love notes","Going on a double date","Slow dancing in the living room","Being the first to apologize"
];
type Phase="setup"|"pass"|"choose"|"judge"|"reveal"|"finished";
type Pick={player:number;card:string};
const deal=(used:string[]=[])=>[...DECK].filter(c=>!used.includes(c)).sort(()=>Math.random()-.5).slice(0,6);

export default function Home(){
 const [players,setPlayers]=useState(["Monica","Makarand","Mira"]),[turnsEach,setTurnsEach]=useState(2),[phase,setPhase]=useState<Phase>("setup"),[turn,setTurn]=useState(0),[step,setStep]=useState(0),[hand,setHand]=useState<string[]>([]),[picks,setPicks]=useState<Pick[]>([]),[scores,setScores]=useState([0,0,0]),[ranking,setRanking]=useState<Pick[]>([]);
 const judge=turn%players.length,choosers=useMemo(()=>players.map((_,i)=>i).filter(i=>i!==judge),[judge,players]),chooser=choosers[step],total=players.length*turnsEach;
 const start=()=>{setScores(players.map(()=>0));setTurn(0);setPicks([]);setStep(0);setPhase("pass")};
 const choose=(card:string)=>{const next=[...picks,{player:chooser,card}];setPicks(next);if(step<choosers.length-1){setStep(step+1);setPhase("pass")}else setPhase("judge")};
 const rank=(first:Pick)=>{const second=picks.find(p=>p!==first)!;setRanking([first,second]);setScores(s=>s.map((n,i)=>n+(i===first.player?2:i===second.player?1:0)));setPhase("reveal")};
 const next=()=>{if(turn+1>=total){setPhase("finished");return}setTurn(turn+1);setStep(0);setPicks([]);setRanking([]);setPhase("pass")};
 const reset=()=>{setPhase("setup");setTurn(0);setPicks([]);setRanking([])};
 const high=Math.max(...scores),winners=players.filter((_,i)=>scores[i]===high);
 return <main className="app-shell">
  <header className="brand-row"><button className="brand" onClick={reset}><span className="brand-mark">?</span><span>Goofy Doofy M3</span></button>{phase!=="setup"&&phase!=="finished"&&<div className="round-pill">Turn {turn+1} of {total}</div>}</header>
  {phase==="setup"&&<section className="setup-screen"><div className="eyebrow">A game about your favorite people</div><h1>How well do you<br/><em>really</em> know each other?</h1><p className="lede">Choose the thing the Whoozit will love most. Read them right, climb the scoreboard.</p><div className="setup-card"><div className="section-heading"><span>Players</span><span className="tiny-label">3 players</span></div><div className="player-inputs">{players.map((p,i)=><label key={i} className="player-input"><span className={`avatar avatar-${i}`}>{p.trim().charAt(0).toUpperCase()||i+1}</span><input value={p} maxLength={18} aria-label={`Player ${i+1} name`} onChange={e=>setPlayers(players.map((n,x)=>x===i?e.target.value:n))}/></label>)}</div><div className="turn-picker"><div><strong>Turns per player</strong><small>About {turnsEach===1?"10":turnsEach===2?"15":"25"} minutes</small></div><div className="segmented">{[1,2,3].map(n=><button key={n} className={turnsEach===n?"active":""} onClick={()=>setTurnsEach(n)}>{n}</button>)}</div></div><button className="primary" disabled={players.some(n=>!n.trim())} onClick={start}>Start the game <span>→</span></button></div><div className="how-it-works"><div><b>1</b><span><strong>Pick secretly</strong><small>Choose what the Whoozit likes</small></span></div><div><b>2</b><span><strong>Rank the picks</strong><small>Favorite earns 2 points</small></span></div><div><b>3</b><span><strong>Know them best</strong><small>Highest score wins</small></span></div></div></section>}
  {phase!=="setup"&&phase!=="finished"&&<div className="score-strip">{players.map((p,i)=><div key={i} className={i===judge?"is-judge":""}><span className={`avatar avatar-${i}`}>{p.charAt(0)}</span><span><small>{i===judge?"WHOOZIT":p}</small><strong>{scores[i]} pts</strong></span></div>)}</div>}
  {phase==="pass"&&<section className="game-screen centered"><div className="pass-icon">↗</div><div className="eyebrow">Keep your cards secret</div><h2>Pass the device to<br/><em>{players[chooser]}</em></h2><p>{players[judge]} is the Whoozit this turn. Pick what you think they’ll like best.</p><button className="primary compact" onClick={()=>{setHand(deal(picks.map(p=>p.card)));setPhase("choose")}}>I’m {players[chooser]} <span>→</span></button></section>}
  {phase==="choose"&&<section className="game-screen"><div className="eyebrow">Choose one for {players[judge]}</div><h2>What would make them <em>smile?</em></h2><p className="instruction">Tap one card. Your choice stays hidden.</p><div className="card-grid">{hand.map((c,i)=><button className={`choice-card card-color-${i}`} key={c} onClick={()=>choose(c)}><span className="card-dot">●</span><strong>{c}</strong><small>CHOOSE THIS</small></button>)}</div></section>}
  {phase==="judge"&&<section className="game-screen centered"><div className="eyebrow">{players[judge]}, you’re the Whoozit</div><h2>Which do you like <em>best?</em></h2><p>Your favorite earns 2 points. The other earns 1.</p><div className="judge-cards">{picks.map(p=><button key={p.card} onClick={()=>rank(p)}><span>♥</span><strong>{p.card}</strong><small>THIS IS MY FAVORITE</small></button>)}</div></section>}
  {phase==="reveal"&&<section className="game-screen centered reveal-screen"><div className="eyebrow">The favorites are in</div><h2>{players[judge]} has <em>spoken!</em></h2><div className="podium"><div className="rank first"><b>1</b><span><small>FAVORITE · +2 PTS</small><strong>{ranking[0]?.card}</strong><em>Played by {players[ranking[0]?.player]}</em></span></div><div className="rank second"><b>2</b><span><small>RUNNER-UP · +1 PT</small><strong>{ranking[1]?.card}</strong><em>Played by {players[ranking[1]?.player]}</em></span></div></div><button className="primary compact" onClick={next}>{turn+1>=total?"See final scores":"Next turn"} <span>→</span></button></section>}
  {phase==="finished"&&<section className="game-screen centered finish-screen"><div className="confetti">✦ · ✦ · ✦</div><div className="eyebrow">That’s the game</div><h2>{winners.join(" & ")} {winners.length>1?"know you best!":"knows you best!"}</h2><div className="final-scores">{players.map((p,i)=><div key={p} className={scores[i]===high?"winner":""}><span className={`avatar avatar-${i}`}>{p.charAt(0)}</span><strong>{p}</strong><b>{scores[i]} <small>pts</small></b></div>)}</div><button className="primary compact" onClick={start}>Play again <span>↻</span></button><button className="text-button" onClick={reset}>Change players</button></section>}
  <footer>Made for Monica, Makarand & Mira <span>♥</span></footer>
 </main>
}
